# Arduino_Cloud

/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/515a7492-07db-4a28-a2d7-ce682c396821 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool led1;
  bool rele1;
  bool rele2;
  bool rele3;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
const int ledPin1 = D0;
const int ledPin2 = D1;
const int ledPin3 = D2;
const int ledPin4 = D3;


void setup() {
  pinMode(ledPin1, OUTPUT);
  pinMode(ledPin2, OUTPUT);
  pinMode(ledPin3, OUTPUT);
  pinMode(ledPin4, OUTPUT);

  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  
}



/*
  Since Led1 is READ_WRITE variable, onLed1Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onLed1Change()  {
    if (led1){
   digitalWrite(ledPin1,HIGH);
}
  else{
    digitalWrite(ledPin1,LOW);
  }
}


/*
  Since Rele1 is READ_WRITE variable, onRele1Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onRele1Change()  {
 if (rele1){
   digitalWrite(ledPin2,HIGH);
}
  else{
    digitalWrite(ledPin2,LOW);
  }
}

/*
  Since Rele2 is READ_WRITE variable, onRele2Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onRele2Change()  {
   if (rele2){
   digitalWrite(ledPin3,HIGH);
}
  else{
    digitalWrite(ledPin3,LOW);
  }
}


/*
  Since Rele3 is READ_WRITE variable, onRele3Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onRele3Change()  {
   if (rele3){
   digitalWrite(ledPin3,HIGH);
}
  else{
    digitalWrite(ledPin3,LOW);
  }
}
